
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: generator-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: generator-platform/project-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: PROJECT_SERVICE_PORT
              value: "8083"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: "generator_platform"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: generator-platform
spec:
  selector:
    app: project-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
